# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WaveForm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'Starscream', '~> 3.0.2'
  pod 'NotificationBannerSwift', '~> 3.0.0'
  pod 'GoogleWebRTC'
  pod 'Alamofire'
  pod 'KeychainAccess', '~> 4.2.0'
  pod 'FloatingPanel'
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwift'
  pod 'CollectionViewPagingLayout'
  # Pods for WaveForm

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end
