# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WaveForm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'Starscream', '~> 3.0.2'
  pod 'NotificationBannerSwift', '~> 3.0.0'
  pod 'GoogleWebRTC'
  pod 'Alamofire'
  pod 'KeychainAccess', '~> 4.2.0'
  pod 'FloatingPanel'
  # Pods for WaveForm

end
